# @package model
_target_: wiser.models.wiser.WISER
embed_dim: 256
num_classes: 1
dropout: 0.1
cdc:
  in_ch: 3
  out_ch: 32
  theta: 0.7
wavelet:
  enabled: true
  use_defocus: true
  high_freq_gate: true
bissm:
  enabled: true
  d_state: 16
  d_conv: 4
  expand: 1
  bidirectional: true
ssca:
  enabled: true
  heads: 1
  dim: 256
compile: false